SELECT
TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') TIMESTAMP,
ID,
LPAD(' ', DEPTH) || OPERATION || ' ' || OPTIONS ||
DECODE(OBJECT_NAME, NULL, NULL, ' (' || OBJECT_NAME || ')')
ACTION,
COST,
CARDINALITY
FROM
DBA_HIST_SQL_PLAN
WHERE
--change sql_id
SQL_ID = 'bngmgmf5gy9bb'
ORDER BY
1 DESC, 2;