SELECT
TO_CHAR(HSS.END_INTERVAL_TIME, 'YYYY-MM-DD HH24:MI:SS') END_INTERVAL_TIME,
HSQ.EXECUTIONS_DELTA EXECUTIONS,
HSQ.ROWS_PROCESSED_DELTA RECORDS,
ROUND(DECODE(HSQ.EXECUTIONS_DELTA, 0, 0, HSQ.ROWS_PROCESSED_DELTA / HSQ.EXECUTIONS_DELTA), 2) RECORDS_PER_EXEC,
HSQ.DISK_READS_DELTA DISK_READS,
ROUND(DECODE(HSQ.EXECUTIONS_DELTA, 0, 0, HSQ.DISK_READS_DELTA / HSQ.EXECUTIONS_DELTA), 2) DISK_READS_PER_EXEC,
HSQ.BUFFER_GETS_DELTA BUFFER_GETS,
ROUND(DECODE(HSQ.EXECUTIONS_DELTA, 0, 0, HSQ.BUFFER_GETS_DELTA / HSQ.EXECUTIONS_DELTA), 2) BUFFER_GETS_PER_EXEC,
ROUND(DECODE(HSQ.ROWS_PROCESSED_DELTA, 0, 0, HSQ.BUFFER_GETS_DELTA / HSQ.ROWS_PROCESSED_DELTA), 2) BUFFER_GETS_PER_RECORD,
HSQ.ELAPSED_TIME_DELTA / 1000 ELAPSED_TIME_MS,
ROUND(DECODE(HSQ.EXECUTIONS_DELTA, 0, 0, HSQ.ELAPSED_TIME_DELTA / HSQ.EXECUTIONS_DELTA / 1000), 3) ELAPSED_TIME_MS_PER_EXEC,
HSQ.CPU_TIME_DELTA / 1000 CPU_TIME_MS,
ROUND(DECODE(HSQ.EXECUTIONS_DELTA, 0, 0, HSQ.CPU_TIME_DELTA / HSQ.EXECUTIONS_DELTA / 1000), 3) CPU_TIME_MS_PER_EXEC
FROM
DBA_HIST_SQLSTAT HSQ, DBA_HIST_SNAPSHOT HSS
WHERE
HSQ.SNAP_ID = HSS.SNAP_ID AND
-- change sql_id here
HSQ.SQL_ID = 'bngmgmf5gy9bb'
ORDER BY
HSS.SNAP_ID DESC;